name: Scancode
on: [push, pull_request]

permissions:
  contents: read

jobs:
  scancode:
    runs-on: ubuntu-latest

    container:
      image: gianlucadb0/scancode-toolkit

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Create results directory
        run: mkdir results

      - name: Scancode run
        run: scancode -clpeui -n 2 --cyclonedx ./results/sbom-cyclonedx --spdx-rdf ./results/sbom-spdx ./

      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: scan-scancode-report
          path: ./results/

      - name: Artifact download
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e
        with:
          name: scan-scancode-report